### ISSUE TITLE
pypi release?

### ISSUE THREAD

**Issue by thiagofigueiro** [opsview/plugnpy#6]
This package doesn't seem to be available on pypi: https://pypi.org/search/?q=plugnpy

Is this intentional?

If you have pypi credentials, the deploy can be easily done by adding something like this to your existing `.travis.yml`.

```yaml
deploy:
  provider: pypi
  user: YOUR_USER
  password:
    secure: YOUR_ENCRYPTED_PASSWORD
  on:
    condition: $TRAVIS_PYTHON_VERSION == '3.6'
    repo:  opsview/plugnpy
    tags: true
  distributions: "sdist bdist_wheel"
```
